title: Matthias Mohs # your name (or website title) here
logo: "/images/portrait.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
As a UX Designer it is my passion to put the user in the center and to advocate his perspective. 
I emphathise with him, search for his motivation and frustration and find the way to optimize this. 
I find the relationship to people, the motivation of their actions, particularly exciting. 

I think design. I focus on simple solutions, for complex problems. 
I think with the pen, multi-dimensional in space and time. 
To me, creativity means finding extraordinary solutions. 
Then the use becomes an experience and the user can identify with the product.

My added value is your customer loyalty. This is what I have understood in my 12 years as an industrial designer.

<br><br>
  
My methodology: 
∙ Design Thinking Process 
∙ Human-centered design 

My toolbox: 
∙ User Research 
∙ Competitor Analysis 
∙ User Interviews 
∙ Data Analysis 
∙ User Persona, -Journey and -Flow 
∙ Wireframing 
∙ Style Guides 
∙ (Interactive) Prototyping 
∙ Usability Testing 

To be able to develop my potential I am looking for a team that has UX in its DNS. 
I am enthusiastic about my job and would like to pass this on to you. 

<br><br>

Curious? More information at Matthiasmohs.de 
Questions? mail@matthiasmohs.de<br>
  <a href="https://www.linkedin.com/in/matthias-mohs/">View My LinkedIn Profile</a> 
  

